Repository githubschool/bigger-picture, pull requests merged in 2022-07, with the labels that each got.

#17 Updates gusshawstewart slide caption
  _slides/02-gusshawstewart.md
Labels: documentation, enhancement

#9 Update 03-guy-man.md
  _slides/03-guy-man.md
Labels: enhancement

#15 Updates on fielpurvis slide caption
  _slides/07-fielpurvis.md
Labels: documentation

#16 Updates slide caption
  _slides/02-gusshawstewart.md
Labels: documentation, enhancement
